read_firefighter_units:
  description: >
    Read a list of firefighter units from the json file {json_file}.
  expected_output: >
    A list of firefighter units with id, x and y coordinates, unit
    type and personnel capacity.
  agent: reader
dispatch_firefighter_unit:
  description: >
    Exclude the units that are unable to respond to this fire event
    with type {fire_type}, severity {fire_severity} and location x,y
    ({location_x}, {location_y}).
    Generate the path to the fire for each one of the units remaining
    in the list.
    Decide which firefighter unit will handle the fire
    event, according to the shortest distance. 
  expected_output: >
    The unit that will cover the incident.
  agent: dispatcher
