read_medical_units:
  description: >
    Read a list of medical units from the json file {json_file}.
  expected_output: >
    A list of medical units with id, x and y coordinates and the
    available beds.
  agent: reader
assign_medical_unit:
  description: >
    Exclude the units with not enough available beds for this fire
    event with {injured_people} injured people.
    Generate the path to the location x,y ({location_x}, {location_y})
    of the fire for each one of the units remaining in the list.
    Decide which unit will cover the fire event, according to the
    shortest distance. 
  expected_output: >
    The unit that will cover the incident.
  agent: balancer
